### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sivasankarp** [mattspaulding/angular-material-kitchen-sink#20]
Hi 

When i tried to debug/run the application i'm getting the following error.
tart
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/APonnurangam/Documents/Sample-Code/MD/angular-material-kitchen-sink-master/npm-debug.log

Kindly guide me in fixing this issue.

**Comment by mattspaulding** [comment]
It is not your fault. The packages were outdated.

Try using v1.1.1
